name: ci/cd pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: run test
        run: |
          go test -v ./...

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: create env file
        run: |
          echo "${{secrets.ENV}}" | base64 --decode > .env
      - name: build docker
        run: docker build --cache-from=type=local,src=/tmp/.build-cache -t filipiketaren/miniproject:1.0.0 .
      - name: docker hub login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: push image
        run: docker push filipiketaren/miniproject:1.0.0

  deploy:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: 'filipiketaren/miniproject:1.0.0'
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Create PEM file from secret
        run: |
          echo "${{ secrets.EC2_PEM }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Deploy to EC2
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            echo "Checking for existing container..."
            if [ \$(sudo docker ps -aq -f name=my-container) ]; then
              echo "Stopping and removing existing container..."
              sudo docker stop my-container || true
              sudo docker rm my-container || true
            fi

            echo "Pulling new image..."
            sudo docker pull $IMAGE_URI

            echo "Starting new container..."
            sudo docker run -d --name my-container -p 8000:8000 $IMAGE_URI

            echo "Deployment complete!"
          EOF

      - name: Clean up PEM file
        run: rm -f ec2-key.pem
